### ISSUE TITLE
Error while resolving packages: com.daltonlima.core

### ISSUE THREAD

**Issue by Pancitus** [daltonbr/Undercooked#2]
Hello, sorry, I would like to open your project on GitHub but when I download the .Zip it gives me some errors in Unity when I open it, could you tell me how I can download and open the project safely without giving me errors?

**Comment by daltonbr** [comment]
Hi,

What Unity version are you using? Currently the project is using `Unity 2020.2.1f1`. You could try using this same version if you are new to Unity.
Look here for the older versions https://unity3d.com/get-unity/download/archive
Otherwise you need to provide more details about the error.

**Comment by Pancitus** [comment]
![image](https://user-images.githubusercontent.com/83099562/115980039-34b1d080-a54f-11eb-95c4-cc605d842b63.png)
![image](https://user-images.githubusercontent.com/83099562/115981228-f1a82b00-a557-11eb-8202-5fffd28804a3.png)
Thank you very much for answering I thought you would not :c
Look at these are the problems I have and I don't have much experience in unity either so if you help me I would appreciate it a lot and a thousand times thanks for your help seriously...

**Comment by daltonbr** [comment]
Thank you for the interest in the project! The error says that we need a dependency (some extra code) that couldn't be imported.
You need to install git on your machine (Unity requires that for downloading those packages). Maybe a restart is needed, then try to import the project again.
https://git-scm.com/
By the way, if you are interested in programming (for Unity or in general) I recommend you to learn at least the basics of Git.
Let me know how it goes.

**Comment by Pancitus** [comment]
Thank you very much I managed to open it now and a curiosity I would like to be able to control the two characters at the same time either on the same device or locally in lan or bluetooth like other games I do not know if you understand me and if so, could you help me with it with a advice or guide? Poss data I think about bringing the game to the Android platform

**Comment by daltonbr** [comment]
I'll close this ticket as the problem was solved before. And even now in the current version, I removed that external package dependency for simplicity's sake.

It is possible to extend the project to multiplayer controllers, as the code was built with that possibility in mind, as the swap player avatars can show. It should be a matter of binding controllers.

For feature requests, such as multiplayer support or mobile port, feel free to open specific tickets for that. Even though I don't have plans to further develop this game. I am considering making some videos on YouTube to talk about the project and do some basic updates on it.
